-- FoundiT Supabase Database Setup Script
-- Run this in your Supabase SQL Editor to ensure your tables match the new UI functionality.

-- 1. Create LostItems table if not exists or ensure columns exist
CREATE TABLE IF NOT EXISTS public."LostItems" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  item_name TEXT NOT NULL,
  date_lost DATE NOT NULL,
  place_lost TEXT NOT NULL,
  reported_by TEXT,
  description TEXT,
  image_url TEXT,
  category TEXT
);

-- 2. Create FoundItems table if not exists or ensure columns exist
CREATE TABLE IF NOT EXISTS public."FoundItems" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  item_name TEXT NOT NULL,
  date_found DATE NOT NULL,
  location_found TEXT NOT NULL,
  turned_in_by TEXT,
  description TEXT,
  image_url TEXT,
  category TEXT
);

-- 3. Enable RLS (Row Level Security) - Optional but recommended
ALTER TABLE public."LostItems" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."FoundItems" ENABLE ROW LEVEL SECURITY;

-- 4. Create public access policies (for development - tighten for production!)
CREATE POLICY "Public Read Access" ON public."LostItems" FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON public."FoundItems" FOR SELECT USING (true);
CREATE POLICY "Public Insert Access" ON public."LostItems" FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Insert Access" ON public."FoundItems" FOR INSERT WITH CHECK (true);

-- 5. Note on Storage
-- Ensure you have a storage bucket named 'item-images' with public access enabled.
