-- FoundiT Supabase Database Setup Script
-- Run this in your Supabase SQL Editor to ensure your tables match the new UI functionality.

-- 1. Create LostItems table if not exists or ensure columns exist
CREATE TABLE IF NOT EXISTS public."LostItems" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  item_name TEXT NOT NULL,
  date_lost DATE NOT NULL,
  place_lost TEXT NOT NULL,
  reported_by TEXT,
  description TEXT,
  image_url TEXT,
  category TEXT
);

-- 2. Create FoundItems table if not exists or ensure columns exist
CREATE TABLE IF NOT EXISTS public."FoundItems" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  item_name TEXT NOT NULL,
  date_found DATE NOT NULL,
  location_found TEXT NOT NULL,
  turned_in_by TEXT,
  description TEXT,
  image_url TEXT,
  category TEXT
);

-- 3. Create Claims table to track reuniting process
CREATE TABLE IF NOT EXISTS public."Claims" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  item_id BIGINT NOT NULL,
  item_type TEXT NOT NULL, -- 'lost' or 'found'
  claimant_name TEXT NOT NULL,
  claimant_id TEXT, -- For student/staff ID
  status TEXT DEFAULT 'pending', -- 'pending', 'verified', 'returned'
  verification_details TEXT
);

-- 4. Enable RLS (Row Level Security)
ALTER TABLE public."LostItems" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."FoundItems" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Claims" ENABLE ROW LEVEL SECURITY;

-- 5. Create public access policies
CREATE POLICY "Public Read Access" ON public."LostItems" FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON public."FoundItems" FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON public."Claims" FOR SELECT USING (true);

CREATE POLICY "Public Insert Access" ON public."LostItems" FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Insert Access" ON public."FoundItems" FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Insert Access" ON public."Claims" FOR INSERT WITH CHECK (true);

-- 6. Note on Storage
-- Ensure you have a storage bucket named 'item-images' with public access enabled.
